#!/bin/bash

. ~/.dot-files/bash/fancy_directory.bash
. ~/.dot-files/bash/ps1.bash

export EDITOR="nvim"
alias vim="nvim"
alias vi="nvim"

alias flushdns="dscacheutil -flushcache"

if [[ $(which hub) ]]; then
  alias git=hub
fi

if [ `uname` = 'Darwin' ]; then
  alias ls='ls -FG'
  alias mv='mv -nv'
else
  alias ls='ls -p --color'
  alias mv='mv -v'
fi

alias ll='ls -lah'

# random env stuff
export ANDROID_HOME=/usr/local/opt/android-sdk
# History: don't store duplicates
export HISTCONTROL=erasedups
# History: 10,000 entries
export HISTSIZE=10000

# PATH
xcode-path() {
  which xcode-select 2>&1 > /dev/null
  if [[ "$?" == "0" ]]; then
    echo $(xcode-select -p)
  else
    echo "/Applications/Xcode.app/Contents/Developer"
  fi
}

export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:~/bin:$(xcode-path)/usr/bin:/usr/local/share/npm/bin:$PATH"

# heroku
export PATH="/usr/local/heroku/bin:$PATH"

# go
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=~

# haskell
export PATH=$PATH:~/.cabal/bin:/Users/myobie/Library/Haskell/bin

# This resolves issues install the mysql, postgres, and other gems with native non universal binary extensions
export ARCHFLAGS='-arch x86_64'

# fzf
export FZF_DEFAULT_COMMAND='ag -g ""'

# node
export NODE_PATH="/usr/local/lib/node_modules"

# colors
export LSCOLORS="exfxcxdxbxegedabagacad"
export CLICOLOR=true

# via mojombo http://gist.github.com/180587
function psg {
  ps wwwaux | egrep "($1|%CPU)" | grep -v grep
}

# sweetness from tim pease
p() {
  if [ -n "$1" ]; then
    ps -O ppid -U $USER | grep -i "$1" | grep -v grep
  else
    ps -O ppid -U $USER
  fi
}

pkill() {
  if [ -z "$1" ]; then
    echo "Usage: pkill [process name]"
    return 1
  fi

  local pid
  pid=$(p $1 | awk '{ print $1 }')

  if [ -n "$pid" ]; then
    echo -n "Killing \"$1\" (process $pid)..."
    kill -9 $pid
    echo "done."
  else
    echo "Process \"$1\" not found."
  fi
}

# bash-completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# git shortcuts
function search-history {
  git log --pretty=format:'%h was %an, %ar, message: %s' | grep $@ | less
}

function clone {
  org=$(echo $1 | awk -F/ '{ print $1 }')
  mkdir -p ~/src/github.com/$org
  path=~/src/github.com/$1
  git clone $@ $path
  cd $path
}

function to {
  query=$1
  result=$(ruby -e 'print 3.times.reduce(["#{ENV.fetch("HOME")}/src"]) { |acc, _| acc.flat_map { |d| Dir["#{d}/**"] } }.select { |d| d.split("/").last =~ /^#{ARGV.first}/ }.first || exit(1)' $1)

  if [[ $? == 0 ]]; then
    cd $result
  else
    echo "No matching directory"
    return 1
  fi
}

# extras that shouldn't be in the repo?
if [ -f ~/.bash_extras  ]; then
  . ~/.bash_extras
fi

# disable control s
stty stop ''

# rbenv
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
